### ISSUE TITLE
How to use this as a package?

### ISSUE THREAD

**Issue by ismailelbadawy** [MaartenGr/soan#2]

**Comment by natlachaman** [comment]
@ismailelbadawy  this configuration of `setup.py` has worked for me:

```python
from setuptools import setup

setup(
    name='SOcial ANalysis',
    url='',
    author='Maarten Grootendorst',
    author_email='maartengrootendorst@gmail.com',
    packages=['soan'],
    description='Used to analyze whatsapp data',
    long_description=open('soan/README.md').read(),
    install_requires=['numpy', 'Pillow', 'scipy', 'sklearn', 'regex', 'emoji', 'seaborn',
                     'datetime', 'pandas', 'requests', 'wordcloud', 'pattern', 'palettable'],
    version='0.1',
    license='MIT',
)
```
**Instructions:**
- Clone repository by typing `git clone https://github.com/MaartenGr/soan.git`.
- Change `setup.py` file with the one proposed above.
- In directory where `soan` folder lies, run `python soan/setup.py install` (you should see `Finished processing dependencies for soan==0.1` if it was successful).
- Check if it was correctly installed by opening python and importing any sub-module. E.g. `from soan.whatssap import helper`.


**NOTE:**  I had issues with some dependencies of `requests` (particularly with `mysql-config` package). Running `sudo apt-get install libmysqlclient-dev` did the trick.

**Comment by ismailelbadawy** [comment]
Thank you @natlachaman . That did the trick.
